### ISSUE TITLE
Report not getting generated with a new xml

### ISSUE THREAD

**Issue by rajatkachhal** [automationeverywhere/soapui-groovy-maven#1]
[soapui-groovy-maven-master 2.zip](https://github.com/automationeverywhere/soapui-groovy-maven/files/1977446/soapui-groovy-maven-master.2.zip)

Hi,

I have attached the sample project with a new xml. When i am executing it reports are not getting generated can you please have a look and suggest me how can i mitigate the same

**Comment by automationeverywhere** [comment]
Hi,

In order to use the framework to generate reports and test data management, we need to call those framework functions in SoapUI setup and teardown scripts at Project, TestSuite and TestCase levels. I missed adding those steps in Readme file. I have now updated the Readme with those missing steps. Please try now after updating setup and teardown scripts.

**Comment by rajatkachhal** [comment]
Thanks for the reply..
I have attached my project can you help me with the tear down scripts for that so that i can learn

**Comment by rajatkachhal** [comment]
or can we write a function in the code itself which automatically adds up this tear down scripts in xml..?

**Comment by automationeverywhere** [comment]
I have updated your sample SoapUI project with setup and teardown scripts. I have executed the tests and reports got generated. Whenever you want to create new tests in SoapUI, clone them from existing tests which will also clone setup and teardown scripts as well. Also you can create one Groovy script in SoapUI to update setup and teardown scripts  in SoapUI.

[SoapUITest-soapui-project.zip](https://github.com/automationeverywhere/soapui-groovy-maven/files/1977699/SoapUITest-soapui-project.zip)

**Comment by rajatkachhal** [comment]
thanks its done
